### ISSUE TITLE
Service does not start

### ISSUE THREAD

**Issue by flouwers** [tofuSCHNITZEL/rpi-screenbrightness-mqtt#4]
The service was working in the past, but not anymore.
It seems python libraries are breaking the code.

Output of `sudo journalctl -u rpi_screenbrightness_mqtt.service`
```
mai 09 17:13:06 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Service hold-off time over, scheduling restart.
mai 09 17:13:06 pi3 systemd[1]: Stopped RasPi Sceeen Brightness Control MQTT.
mai 09 17:13:06 pi3 systemd[1]: Started RasPi Sceeen Brightness Control MQTT.
mai 09 17:13:06 pi3 python3[18239]: Traceback (most recent call last):
mai 09 17:13:06 pi3 python3[18239]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
mai 09 17:13:06 pi3 python3[18239]:     "__main__", mod_spec)
mai 09 17:13:06 pi3 python3[18239]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
mai 09 17:13:06 pi3 python3[18239]:     exec(code, run_globals)
mai 09 17:13:06 pi3 python3[18239]:   File "/usr/local/lib/python3.5/dist-packages/rpi_screenbrightness_mqtt-0.5.0-py3.5.egg/rpi_screenbrightness_mqtt/run.py", line 7,
mai 09 17:13:06 pi3 python3[18239]:   File "/usr/local/lib/python3.5/dist-packages/rpi_backlight/__init__.py", line 55
mai 09 17:13:06 pi3 python3[18239]:     f"board_type must be a member of the BoardType enum, got {type(board_type)}"
mai 09 17:13:06 pi3 python3[18239]:                                                                                ^
mai 09 17:13:06 pi3 python3[18239]: SyntaxError: invalid syntax
mai 09 17:13:06 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Main process exited, code=exited, status=1/FAILURE
mai 09 17:13:06 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Unit entered failed state.
mai 09 17:13:06 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Failed with result 'exit-code'.
```

**Comment by tofuSCHNITZEL** [comment]
I think you need to update your python...
https://pypi.org/project/rpi-backlight/
does not list python3.5 as compatible.

**Comment by flouwers** [comment]
Hello.
Thanks for the info.
Manually installing pyhton 3.9 solves the problem.

However, I had to change the service config file, because the ExeStart path is not absolute:

```
systemctl status rpi_screenbrightness_mqtt.service
● rpi_screenbrightness_mqtt.service - RasPi Sceeen Brightness Control MQTT
   Loaded: loaded (/etc/systemd/system/rpi_screenbrightness_mqtt.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-05-10 11:24:13 CEST; 3min 57s ago
 Main PID: 1751 (code=exited, status=1/FAILURE)

mai 10 11:24:10 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Unit entered failed state.
mai 10 11:24:10 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Failed with result 'exit-code'.
mai 10 11:24:13 pi3 systemd[1]: [/etc/systemd/system/rpi_screenbrightness_mqtt.service:7] Executable path is not absolute, ignoring: python3 -u -m rpi_screenbrightness_
mai 10 11:24:13 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
mai 10 11:24:13 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Service hold-off time over, scheduling restart.
mai 10 11:24:13 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Failed to schedule restart job: Unit rpi_screenbrightness_mqtt.service is not loaded properly: Invali
mai 10 11:24:13 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Unit entered failed state.
mai 10 11:24:13 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Failed with result 'exit-code'.
mai 10 11:24:13 pi3 systemd[1]: [/etc/systemd/system/rpi_screenbrightness_mqtt.service:7] Executable path is not absolute, ignoring: python3 -u -m rpi_screenbrightness_
mai 10 11:24:13 pi3 systemd[1]: rpi_screenbrightness_mqtt.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

Simply added '/usr/bin' does the trick.

**Comment by tofuSCHNITZEL** [comment]
thanks, I have updated the file!
